### PR TITLE
simx86: use a BrokenCodePtr variable to only keep JIT code alive for …

### LINKED ISSUE #2708: Crash in simx86 JIT: “ERROR: Fault 13 in jit-compiled code” / ERROR: Bad exec address 0x78cb7f6ef711
**Describe the bug**
When running my legacy DOS application under dosemu2 built from current git sources, dosemu2 crashes shortly after the program starts. With `$_cpu_vm=emulated` I get a ERROR: Fault 13 in jit-compiled code, with `$_cpu_vm=kvm` it's ERROR: Bad exec address 0x78cb7f6ef711.

Furthermore, if I do `$_cpuemu = (1)` (interpreter) it doesn't seem to happen.

**To Reproduce**
At the moment I can't trace it back to specific steps but it happens so regularly that I can provoke it to occur seemingly random. I attached 3 logs from different attempts.

**Attach program/game binaries or provide an URL**
Can provide per mail

**Attach the log**

[boot.log](https://github.com/user-attachments/files/24020328/boot.log)

[boot_1.log](https://github.com/user-attachments/files/24020329/boot_1.log)

[boot_kvm.log](https://github.com/user-attachments/files/24020434/boot_kvm.log)

**A regression?**
Worked in dosemu2-2.0pre6 with ubuntu 16.04

**dosemu2 origins**
From git

```
./default-configure --disable-dj64 --disable-searpc
Enabling plugins: 
	X 
	Xkmaps 
	alsa 
	charsets 
	console 
	dnative 
	doscmd 
	dosdrv 
	extra_charsets 
	fdpp 
	json 
	midimisc 
	modemu 
	msdos 
	periph 
	sdl

configure: WARNING: dj64dev not available!

configure: WARNING: searpc not available!

```

**Additional info**
freecom

Tried with emulated and kvm, see logs

**I can stick to interpreter for my use case to avoid this crash.**

### PR DESCRIPTION
**Pull request by bartoldeman**
…a bit

This way all the rest for the node can be deleted, and there is no need for dead nodes any more.

Also pass the correct jit pointer from sigsegv.c to TryInvalidateNodeRange()

Fixes #2708

### CODE REVIEW

File: src/base/emu-i386/simx86/trees.c [hunk 1]
```diff
@@ -1399,9 +1400,9 @@ void InvalidateNodeRange(int al, int len)
   DoInvalidateNodeRange(al, len, NULL, NULL);
 }
 
-int TryInvalidateNodeRange(int al, int len, unsigned char *eip)
+void TryInvalidateNodeRange(int al, int len, unsigned char *eip)
```
Comment (stsp) [inline src/base/emu-i386/simx86/trees.c]: Maybe also the name
should be changed, as
"Try" was because it
could be interrupted.
Maybe something with
"FromFault" suffix or
alike?

File: src/base/emu-i386/simx86/trees.c [hunk 2]
```diff
@@ -1399,9 +1400,9 @@ void InvalidateNodeRange(int al, int len)
   DoInvalidateNodeRange(al, len, NULL, NULL);
```
Comment (stsp) [inline src/base/emu-i386/simx86/trees.c:1403]: Just move FreeGenCodeBuf() here?

Comment (bartoldeman) [reply src/base/emu-i386/simx86/trees.c:1403]: You mean from codegen.c? I'm not sure if that's safe, what if TryInvalidateNodeRange is called twice in a row? I'd rather have it free()ed it ASAP.

File: src/base/emu-i386/simx86/trees.c (hunk 1 above)
Comment (bartoldeman) [reply src/base/emu-i386/simx86/trees.c]: ok

File: src/base/emu-i386/simx86/trees.c (hunk 2 above)
Comment (bartoldeman) [reply src/base/emu-i386/simx86/trees.c:1403]: it's also possible to move `FreeGenCodeBuf()` out of `RemoveNode_unlocked`, towards the callers, that would eliminate the boolean keepnode.

Comment (stsp) [reply src/base/emu-i386/simx86/trees.c:1403]: Exactly! :)

Comment (bartoldeman) [reply src/base/emu-i386/simx86/trees.c:1403]: done, though it is important to call `FreeGenCodeBuf()` after the rest since `NodeUnlinker()` relies on a still-valid `G->addr`.

File: src/base/emu-i386/simx86/trees.c [hunk 3]
```diff
@@ -1373,14 +1372,19 @@ static int DoInvalidateNodeRange(int al, int len, unsigned char *eip,
...
+	    if (eip && hook) {
+		p = hook(G, eip);
+		if (p)
+		    rc = p;
+	    }
 	    if (debug_level('e')>2) e_printf("Delete node %08x\n",G->key);
+	    unsigned char *q = G->addr;
 	    RemoveNode_unlocked(G);
+	    if (p == NULL)
+		FreeGenCodeBuf(q);
```
Comment (stsp) [inline src/base/emu-i386/simx86/trees.c:1387]: But you can return that
addr 1 frame further, as
you do already for self-hit.

Comment (bartoldeman) [reply src/base/emu-i386/simx86/trees.c:1387]: I don't think so unless I misunderstand: there can only be one self-hit but there can be multiple nodes removed: I'd have to create a list if I remove them in an outer frame

Comment (stsp) [reply src/base/emu-i386/simx86/trees.c:1387]: You can return only a
self-hit one or NULL.
You already do the same
for FromFault variant.

Comment (stsp) [reply src/base/emu-i386/simx86/trees.c:1387]: Ah, there is no self-hit
possible for non-fault
variant! Sorry.

**Comment by stsp** [comment]
Thanks!
Looks great. :)
